version: "1"
rules:
  - base: main
    upstream: hanghae-last-week:master    # change `wei` to the owner of upstream repo
    mergeMethod: hardreset
  - base: develop
    upstream: hanghae-last-week:develop    # change `wei` to the owner of upstream repo
    mergeMethod: hardreset